## What is Pandas?

- **Pandas** is a powerful Python library used for **data analysis and data manipulation**.
- It is built on top of **NumPy**.
- It provides easy tools to work with **structured data (tables)**.
- Pandas is widely used in:
  - Data Science
  - Machine Learning
  - Finance
  - Data Engineering
  - Research

Main features:

- Easy data loading (CSV, Excel, JSON, SQL)
- Data cleaning and transformation
- Data aggregation and analysis
- Time series support
- Integration with visualization libraries

```bash
!pip install pandas
```

---

# Core Data Structures

Pandas provides two main data structures.

## 1️⃣ Series

- A **Series** is a one-dimensional labeled array.
- Similar to a column in a table.

In [1]:
import pandas as pd

data = pd.Series([10,20,30,40])

print(data)

0    10
1    20
2    30
3    40
dtype: int64

## 2️⃣ DataFrame

* A **DataFrame** is a two-dimensional table.
* Similar to an **Excel sheet or SQL table**.
* Rows → records
* Columns → variables

In [2]:
data = {
    "Name": ["Alice","Bob","Charlie"],
    "Age": [25,30,35],
    "City": ["NY","LA","Chicago"]
}

df = pd.DataFrame(data)

print(df)

      Name  Age     City
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago

---

# Creating DataFrames

In [3]:
# From Dictionary
df = pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6]
})
df

   A  B
0  1  4
1  2  5
2  3  6

In [4]:
# From List
data = [
    ["Alice",25],
    ["Bob",30]
]

df = pd.DataFrame(data, columns=["Name","Age"])
df

    Name  Age
0  Alice   25
1    Bob   30

# Reading Data (Very Common)
Pandas supports many file formats.

In [5]:
file_name = r"db\demo_student_marksheet_dataset.csv"

In [6]:
df = pd.read_csv(file_name)

In [7]:
# Excel, json etc

In [8]:
# pd.read

# Viewing Data

In [9]:
# First rows
df.head()

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage
0,300657,Dasan,21,Nadodikkattu,68,85,64,59,82,68,77,70,79,652,72.444444
1,300658,Vijayan,16,Nadodikkattu,94,60,53,77,56,71,55,88,56,610,67.777778
2,300659,Ramanan,18,Punjabi House,69,75,73,40,82,71,84,90,75,659,73.222222
3,300660,Mannar Mathai,20,Ramji Rao Speaking,93,75,89,85,72,69,62,57,98,700,77.777778
4,300661,Gopalakrishnan,15,Godfather,88,75,67,54,60,64,73,99,72,652,72.444444

In [10]:
# Last rows
df.tail()

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage
74,300731,Soumya,21,Maheshinte Prathikaaram,62,80,92,98,84,88,51,74,64,693,77.000000
75,300732,Kannan,21,Minnal Murali,54,59,75,71,74,58,74,81,45,591,65.666667
76,300733,Josemon,21,Minnal Murali,80,69,92,55,88,61,64,56,55,620,68.888889
77,300734,Shibu,19,Minnal Murali,43,43,49,42,58,49,60,45,59,448,49.777778
78,300735,Dashamoolam Damu,21,Chattambinadu,40,57,82,54,52,72,88,58,56,559,62.111111

In [11]:
# Data summary
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Student_ID              79 non-null     int64
 1   Name                    79 non-null     str
 2   Age                     79 non-null     int64
 3   Address                 79 non-null     str
 4   Malayalam               79 non-null     int64
 5   English                 79 non-null     int64
 6   Hindi                   79 non-null     int64
 7   Social_Science          79 non-null     int64
 8   Physics                 79 non-null     int64
 9   Chemistry               79 non-null     int64
 10  Biology                 79 non-null     int64
 11  Mathematics             79 non-null     int64
 12  Information_Technology  79 non-null     int64
 13  Total                   79 non-null     int64
 14  Percentage              79 non-null     float64
dtypes: float64(1), int64(12), str(2)
memory usage: 9.4 KB

In [12]:
# Statistics
df.describe()

,Student_ID,Age,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage
count,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000
mean,300696.000000,18.392405,66.670886,63.012658,67.126582,65.506329,65.443038,71.025316,64.253165,64.898734,66.924051,594.860759,66.095640
std,22.949219,2.174548,16.137805,15.205847,16.587273,16.531922,16.537252,14.730027,14.578231,17.363825,16.963590,77.868353,8.652039
min,300657.000000,15.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,418.000000,46.444444
25%,300676.500000,17.000000,53.500000,52.500000,53.000000,53.500000,53.000000,60.000000,53.500000,53.000000,54.000000,555.500000,61.722222
50%,300696.000000,18.000000,66.000000,59.000000,65.000000,62.000000,62.000000,71.000000,62.000000,62.000000,65.000000,608.000000,67.555556
75%,300715.500000,20.000000,80.500000,75.000000,82.000000,82.000000,82.000000,82.500000,73.000000,78.000000,78.500000,651.000000,72.333333
max,300735.000000,22.000000,94.000000,95.000000,98.000000,98.000000,100.000000,99.000000,100.000000,99.000000,99.000000,773.000000,85.888889

# Selecting Data

In [13]:
# Select column
df["Name"]

0                Dasan
1              Vijayan
2              Ramanan
3        Mannar Mathai
4       Gopalakrishnan
            ...
74              Soumya
75              Kannan
76             Josemon
77               Shibu
78    Dashamoolam Damu
Name: Name, Length: 79, dtype: str

In [14]:
# Multiple columns
df[["Name","Age"]]

                Name  Age
0              Dasan   21
1            Vijayan   16
2            Ramanan   18
3      Mannar Mathai   20
4     Gopalakrishnan   15
..               ...  ...
74            Soumya   21
75            Kannan   21
76           Josemon   21
77             Shibu   19
78  Dashamoolam Damu   21

[79 rows x 2 columns]

In [15]:
# Select rows
df.iloc[0]

Student_ID                      300657
Name                             Dasan
Age                                 21
Address                   Nadodikkattu
Malayalam                           68
English                             85
Hindi                               64
Social_Science                      59
Physics                             82
Chemistry                           68
Biology                             77
Mathematics                         70
Information_Technology              79
Total                              652
Percentage                   72.444444
Name: 0, dtype: object

In [16]:
# Label based selection
df.loc[0]

Student_ID                      300657
Name                             Dasan
Age                                 21
Address                   Nadodikkattu
Malayalam                           68
English                             85
Hindi                               64
Social_Science                      59
Physics                             82
Chemistry                           68
Biology                             77
Mathematics                         70
Information_Technology              79
Total                              652
Percentage                   72.444444
Name: 0, dtype: object

In [17]:
# Filtering Data
df[df["Malayalam"]< 100]

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage
0,300657,Dasan,21,Nadodikkattu,68,85,64,59,82,68,77,70,79,652,72.444444
1,300658,Vijayan,16,Nadodikkattu,94,60,53,77,56,71,55,88,56,610,67.777778
2,300659,Ramanan,18,Punjabi House,69,75,73,40,82,71,84,90,75,659,73.222222
3,300660,Mannar Mathai,20,Ramji Rao Speaking,93,75,89,85,72,69,62,57,98,700,77.777778
4,300661,Gopalakrishnan,15,Godfather,88,75,67,54,60,64,73,99,72,652,72.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,300731,Soumya,21,Maheshinte Prathikaaram,62,80,92,98,84,88,51,74,64,693,77.000000
75,300732,Kannan,21,Minnal Murali,54,59,75,71,74,58,74,81,45,591,65.666667
76,300733,Josemon,21,Minnal Murali,80,69,92,55,88,61,64,56,55,620,68.888889
77,300734,Shibu,19,Minnal Murali,43,43,49,42,58,49,60,45,59,448,49.777778
78,300735,Dashamoolam Damu,21,Chattambinadu,40,57,82,54,52,72,88,58,56,559,62.111111

In [18]:
df["Malayalam"] .describe()

count    79.000000
mean     66.670886
std      16.137805
min      40.000000
25%      53.500000
50%      66.000000
75%      80.500000
max      94.000000
Name: Malayalam, dtype: float64

In [19]:
# Multiple conditions
df[(df["Malayalam"] > 90) & (df["Hindi"] < 50)]

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage
12,300669,Thorappan Kochunni,18,CID Moosa,93,54,44,44,98,67,74,60,52,586,65.111111

In [20]:
# Adding and Modifying Columns
df["Average_Mark"] = df["Total"] / 9

df.head()

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage,Average_Mark
0,300657,Dasan,21,Nadodikkattu,68,85,64,59,82,68,77,70,79,652,72.444444,72.444444
1,300658,Vijayan,16,Nadodikkattu,94,60,53,77,56,71,55,88,56,610,67.777778,67.777778
2,300659,Ramanan,18,Punjabi House,69,75,73,40,82,71,84,90,75,659,73.222222,73.222222
3,300660,Mannar Mathai,20,Ramji Rao Speaking,93,75,89,85,72,69,62,57,98,700,77.777778,77.777778
4,300661,Gopalakrishnan,15,Godfather,88,75,67,54,60,64,73,99,72,652,72.444444,72.444444

# Removing Data

In [21]:
# Drop column
df.drop(columns=["Average_Mark"])

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage
0,300657,Dasan,21,Nadodikkattu,68,85,64,59,82,68,77,70,79,652,72.444444
1,300658,Vijayan,16,Nadodikkattu,94,60,53,77,56,71,55,88,56,610,67.777778
2,300659,Ramanan,18,Punjabi House,69,75,73,40,82,71,84,90,75,659,73.222222
3,300660,Mannar Mathai,20,Ramji Rao Speaking,93,75,89,85,72,69,62,57,98,700,77.777778
4,300661,Gopalakrishnan,15,Godfather,88,75,67,54,60,64,73,99,72,652,72.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,300731,Soumya,21,Maheshinte Prathikaaram,62,80,92,98,84,88,51,74,64,693,77.000000
75,300732,Kannan,21,Minnal Murali,54,59,75,71,74,58,74,81,45,591,65.666667
76,300733,Josemon,21,Minnal Murali,80,69,92,55,88,61,64,56,55,620,68.888889
77,300734,Shibu,19,Minnal Murali,43,43,49,42,58,49,60,45,59,448,49.777778
78,300735,Dashamoolam Damu,21,Chattambinadu,40,57,82,54,52,72,88,58,56,559,62.111111

In [22]:
# Drop row
df.drop(index=0)

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage,Average_Mark
1,300658,Vijayan,16,Nadodikkattu,94,60,53,77,56,71,55,88,56,610,67.777778,67.777778
2,300659,Ramanan,18,Punjabi House,69,75,73,40,82,71,84,90,75,659,73.222222,73.222222
3,300660,Mannar Mathai,20,Ramji Rao Speaking,93,75,89,85,72,69,62,57,98,700,77.777778,77.777778
4,300661,Gopalakrishnan,15,Godfather,88,75,67,54,60,64,73,99,72,652,72.444444,72.444444
5,300662,Appukuttan,21,In Harihar Nagar,77,71,80,89,84,84,55,72,97,709,78.777778,78.777778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,300731,Soumya,21,Maheshinte Prathikaaram,62,80,92,98,84,88,51,74,64,693,77.000000,77.000000
75,300732,Kannan,21,Minnal Murali,54,59,75,71,74,58,74,81,45,591,65.666667,65.666667
76,300733,Josemon,21,Minnal Murali,80,69,92,55,88,61,64,56,55,620,68.888889,68.888889
77,300734,Shibu,19,Minnal Murali,43,43,49,42,58,49,60,45,59,448,49.777778,49.777778
78,300735,Dashamoolam Damu,21,Chattambinadu,40,57,82,54,52,72,88,58,56,559,62.111111,62.111111

# Handling Missing Data
Missing values are common in real datasets
    Check missing values.

In [23]:
# Check missing values
df.isnull()

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage,Average_Mark
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
76,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
78,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [24]:
# Drop missing values
df.dropna()

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage,Average_Mark
0,300657,Dasan,21,Nadodikkattu,68,85,64,59,82,68,77,70,79,652,72.444444,72.444444
1,300658,Vijayan,16,Nadodikkattu,94,60,53,77,56,71,55,88,56,610,67.777778,67.777778
2,300659,Ramanan,18,Punjabi House,69,75,73,40,82,71,84,90,75,659,73.222222,73.222222
3,300660,Mannar Mathai,20,Ramji Rao Speaking,93,75,89,85,72,69,62,57,98,700,77.777778,77.777778
4,300661,Gopalakrishnan,15,Godfather,88,75,67,54,60,64,73,99,72,652,72.444444,72.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,300731,Soumya,21,Maheshinte Prathikaaram,62,80,92,98,84,88,51,74,64,693,77.000000,77.000000
75,300732,Kannan,21,Minnal Murali,54,59,75,71,74,58,74,81,45,591,65.666667,65.666667
76,300733,Josemon,21,Minnal Murali,80,69,92,55,88,61,64,56,55,620,68.888889,68.888889
77,300734,Shibu,19,Minnal Murali,43,43,49,42,58,49,60,45,59,448,49.777778,49.777778
78,300735,Dashamoolam Damu,21,Chattambinadu,40,57,82,54,52,72,88,58,56,559,62.111111,62.111111

In [25]:
# Fill missing values
df.fillna(0)

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage,Average_Mark
0,300657,Dasan,21,Nadodikkattu,68,85,64,59,82,68,77,70,79,652,72.444444,72.444444
1,300658,Vijayan,16,Nadodikkattu,94,60,53,77,56,71,55,88,56,610,67.777778,67.777778
2,300659,Ramanan,18,Punjabi House,69,75,73,40,82,71,84,90,75,659,73.222222,73.222222
3,300660,Mannar Mathai,20,Ramji Rao Speaking,93,75,89,85,72,69,62,57,98,700,77.777778,77.777778
4,300661,Gopalakrishnan,15,Godfather,88,75,67,54,60,64,73,99,72,652,72.444444,72.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,300731,Soumya,21,Maheshinte Prathikaaram,62,80,92,98,84,88,51,74,64,693,77.000000,77.000000
75,300732,Kannan,21,Minnal Murali,54,59,75,71,74,58,74,81,45,591,65.666667,65.666667
76,300733,Josemon,21,Minnal Murali,80,69,92,55,88,61,64,56,55,620,68.888889,68.888889
77,300734,Shibu,19,Minnal Murali,43,43,49,42,58,49,60,45,59,448,49.777778,49.777778
78,300735,Dashamoolam Damu,21,Chattambinadu,40,57,82,54,52,72,88,58,56,559,62.111111,62.111111

---

# Sorting Data

In [26]:
# Sort by column
df.sort_values("Age")

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage,Average_Mark
4,300661,Gopalakrishnan,15,Godfather,88,75,67,54,60,64,73,99,72,652,72.444444,72.444444
15,300672,Adv. Lal Krishna Viradiyar,15,Godfather,77,55,58,91,53,58,94,61,59,606,67.333333,67.333333
26,300683,Thankappan,15,Punjabi House,56,54,48,45,56,54,51,58,52,474,52.666667,52.666667
59,300716,Vasu,15,Kunjiramayanam,84,91,88,62,63,79,43,43,78,631,70.111111,70.111111
61,300718,Babumon,15,Salt N Pepper,47,49,59,59,53,53,54,55,54,483,53.666667,53.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,300679,Kottappally Prabhakaran,22,Sandesham,57,59,73,92,83,89,72,51,54,630,70.000000,70.000000
19,300676,Pyari,22,Kalyanaraman,89,54,40,45,74,76,75,71,88,612,68.000000,68.000000
51,300708,Pappu Chettan,22,Aadu,84,72,73,59,82,59,80,61,88,658,73.111111,73.111111
65,300722,Kunjappan Robot,22,Android Kunjappan,80,40,63,78,83,82,53,71,73,623,69.222222,69.222222
70,300727,Kora,22,Sudani From Nigeria,63,40,84,58,50,67,40,72,53,527,58.555556,58.555556

In [27]:
# Descending
df.sort_values("Age", ascending=False)

,Student_ID,Name,Age,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage,Average_Mark
46,300703,Raj Bose,22,Happy Husbands,41,64,41,87,41,95,55,52,81,557,61.888889,61.888889
70,300727,Kora,22,Sudani From Nigeria,63,40,84,58,50,67,40,72,53,527,58.555556,58.555556
65,300722,Kunjappan Robot,22,Android Kunjappan,80,40,63,78,83,82,53,71,73,623,69.222222,69.222222
51,300708,Pappu Chettan,22,Aadu,84,72,73,59,82,59,80,61,88,658,73.111111,73.111111
22,300679,Kottappally Prabhakaran,22,Sandesham,57,59,73,92,83,89,72,51,54,630,70.000000,70.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,300705,Kunjunni,15,Kilichundan Mampazham,63,91,85,83,59,82,43,94,65,665,73.888889,73.888889
50,300707,Velayudhan,15,Chattambinadu,50,55,70,70,41,75,83,85,59,588,65.333333,65.333333
59,300716,Vasu,15,Kunjiramayanam,84,91,88,62,63,79,43,43,78,631,70.111111,70.111111
58,300715,Ambrose,15,Kunjiramayanam,82,42,80,60,69,79,100,90,40,642,71.333333,71.333333
68,300725,Jibi,15,Romancham,46,41,50,44,48,47,60,54,52,442,49.111111,49.111111

---

# Grouping Data (Very Powerful)

Used for aggregation.

In [28]:
df.groupby("Age")["Malayalam"].mean()

Age
15    67.400000
16    66.000000
17    69.333333
18    61.900000
19    67.416667
20    66.200000
21    66.272727
22    69.000000
Name: Malayalam, dtype: float64

In [29]:
df.groupby("Age").sum()

,Student_ID,Name,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage,Average_Mark
Age,,,,,,,,,,,,,,,
15,3006997,GopalakrishnanAdv. Lal Krishna ViradiyarThanka...,GodfatherGodfatherPunjabi HouseThilakkamKilich...,674,635,692,628,571,690,669,729,604,5892,654.666667,654.666667
16,2405583,VijayanSundaranKunjoonjuMandrakeKunjappuKurish...,NadodikkattuPulival KalyanamEe Parakkum Thalik...,528,464,494,555,440,585,451,560,509,4586,509.555556,509.555556
17,3608281,MahadevanArjunShaji PappanKannan SrankThalathi...,In Harihar NagarCID MoosaAaduMayaviVadakkunokk...,832,821,732,781,822,941,751,760,831,7271,807.888889,807.888889
18,3006956,RamananThorappan KochunniSankaran KuttyUrumis ...,Punjabi HouseCID MoosaVettamKochi RajavuRamji ...,619,587,643,521,707,622,649,575,640,5563,618.111111,618.111111
19,3608346,NischalPonnappanAravindanPeethambaranVeerappan...,KilukkamMeesa MadhavanChithramCID MoosaMannar ...,809,755,873,856,779,882,804,787,881,7426,825.111111,825.111111
20,3006852,Mannar MathaiGovindan KuttyThomaskuttyPachalam...,Ramji Rao SpeakingIn Harihar NagarIn Harihar N...,662,665,673,625,641,658,675,585,672,5856,650.666667,650.666667
21,3307754,DasanAppukuttanAdv. GovindanKunjikannanAvarach...,NadodikkattuIn Harihar NagarRamji Rao Speaking...,729,722,822,790,797,765,702,753,713,6793,754.777778,754.777778
22,1804215,PyariKottappally PrabhakaranRaj BosePappu Chet...,KalyanaramanSandeshamHappy HusbandsAaduAndroid...,414,329,374,419,413,468,375,378,437,3607,400.777778,400.777778

In [30]:
df.groupby("Age").count()

,Student_ID,Name,Address,Malayalam,English,Hindi,Social_Science,Physics,Chemistry,Biology,Mathematics,Information_Technology,Total,Percentage,Average_Mark
Age,,,,,,,,,,,,,,,
15,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
16,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
17,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
18,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
19,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
20,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
21,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
22,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6

---

# Writing Data

Save processed data.

In [31]:
# save the modified DataFrame to a new CSV file
out_file_name = r"output.csv"
with open(out_file_name, "w") as f:
    df.to_csv(f, index=False)